---
kind: pipeline
type: docker
name: linux-arm64

platform:
  arch: arm64
  os: linux

steps:
  - name: docker-build
    image: plugins/docker
    settings:
      repo: test
      dry_run: true
      tags:
        - ${DRONE_COMMIT_SHA}
    when:
      ref:
        include:
        - refs/pull/**
  
  - name: docker-build-tag
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo:
        from_secret: docker_repo
      tags:
        - linux-arm64
        - "${DRONE_TAG}-linux-arm64"
    when:
      event:
        - tag

---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps: 
  - name: docker-build
    image: plugins/docker
    settings:
      repo: test
      dry_run: true
      tags:
        - ${DRONE_COMMIT_SHA}
    when:
      ref:
        include:
        - refs/pull/**
  
  - name: docker-build-tag
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo:
        from_secret: docker_repo
      tags:
        - linux-amd64
        - "${DRONE_TAG}-linux-amd64"
    when:
      event:
        - tag

trigger:
  ref:
    include:
    - refs/pull/**
    - refs/tags/**

---
kind: pipeline
type: docker
name: build-all

platform:
  arch: amd64
  os: linux

environment:
  DOCKER_REPO:
    from_secret: docker_repo

steps:
  - name: manifest-tag
    image: plugins/manifest
    settings:
      auto_tag: "true"
      ignore_missing: "true"
      target: "${DOCKER_REPO}:${DRONE_TAG}"
      template: "${DOCKER_REPO}:${DRONE_TAG}-OS-ARCH"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      event:
        - tag

  - name: manifest-latest
    image: plugins/manifest
    settings:
      auto_tag: "true"
      ignore_missing: "true"
      target: "${DOCKER_REPO}:latest"
      template: "${DOCKER_REPO}:OS-ARCH"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      event:
        - tag

depends_on:
- linux-amd64
- linux-arm64

trigger:
  ref:
    include:
    - refs/tags/**