---
kind: pipeline
type: docker
name: linux-arm64

platform:
  arch: arm64
  os: linux

steps:
  - name: docker-build
    image: plugins/docker
    settings:
      repo: test
      dry_run: true
      tags:
        - ${DRONE_COMMIT_SHA}
    when:
      ref:
        include:
        - refs/pull/**
  
  - name: docker-build-tag
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo:
        from_secret: docker_repo
      tags:
        - latest
        - "${DRONE_TAG}"
    when:
      event:
        - tag

---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps: 
  - name: docker-build
    image: plugins/docker
    settings:
      repo: test
      dry_run: true
      tags:
        - ${DRONE_COMMIT_SHA}
    when:
      ref:
        include:
        - refs/pull/**
  
  - name: docker-build-tag
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo:
        from_secret: docker_repo
      tags:
        - latest
        - "${DRONE_TAG}"
    when:
      event:
        - tag

trigger:
  ref:
    include:
    - refs/pull/**
    - refs/tags/**

---
kind: pipeline
type: docker
name: build-all

steps: []

depends_on:
- linux-amd64
- linux-arm64

trigger:
  ref:
    include:
    - refs/pull/**
    - refs/tags/**